# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Test Python Package

on:
  push:
    paths-ignore:
      - "**/README.md"

permissions:
  contents: read

jobs:
  test-python3-10:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        #pip install -r requirements.txt
        pip install poetry
    - name: Build package
      id: build
      run: poetry build
    - name: TOML Reader
      if: ${{ steps.build.outcome }} == "success"
      uses: SebRollen/toml-action@v1.0.2
      id: read_toml
      with:
        file: "pyproject.toml"
        field: "tool.poetry.version"
    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: notpy tar.gz
        path: ./dist/notpy-${{ steps.read_toml.outputs.value }}.tar.gz

    - name: Install package
      id: install
      run:  |
        echo "Version: ${{ steps.read_toml.outputs.value }}"
        ls ./dist -lah
        pip install ./dist/notpy-${{ steps.read_toml.outputs.value }}.tar.gz
        ls -lah /opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/notpy/modules/
    - name: Test package
      if: ${{ steps.install.outcome }} == "success"
      run:  |
        ./tests/test.sh
  
  # test-python3-11:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Set up Python
  #     uses: actions/setup-python@v3
  #     with:
  #       python-version: '3.11'
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install poetry
  #   - name: Build package
  #     run: poetry build
  #   - name: TOML Reader
  #     uses: SebRollen/toml-action@v1.0.2
  #     id: read_toml
  #     with:
  #       file: "pyproject.toml"
  #       field: "tool.poetry.version"
  #   - name: Test package
  #     run:  |
  #       echo "Version: ${{ steps.read_toml.outputs.value }}"
  #       ls ./dist -lah
  #       pip install ./dist/notpy-${{ steps.read_toml.outputs.value }}.tar.gz \
  #       notpy help
  
  # test-python3-12:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Set up Python
  #     uses: actions/setup-python@v3
  #     with:
  #       python-version: '3.12'
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install poetry
  #   - name: Build package
  #     run: poetry build
  #   - name: TOML Reader
  #     uses: SebRollen/toml-action@v1.0.2
  #     id: read_toml
  #     with:
  #       file: "pyproject.toml"
  #       field: "tool.poetry.version"
  #   - name: Test package
  #     run:  |
  #       echo "Version: ${{ steps.read_toml.outputs.value }}"
  #       ls ./dist -lah
  #       pip install ./dist/notpy-${{ steps.read_toml.outputs.value }}.tar.gz \
  #       notpy help
    
